### ISSUE TITLE
make source for this repo public and link it from the html version

### ISSUE THREAD

**Issue by JanZerebecki** [SUSE/suse.github.io#18]
While it is easier to find https://opensource.suse.com/suse-open-source-policy then getting to this repo or even finding https://github.com/SUSE/open-source-policy is harder.

Make https://github.com/SUSE/open-source-policy public, it is currently the source for this repo.

In it referencethe rendered version, currently this repo, and how to update it from the source.

Link to the source from the html version.

**Comment by sysrich** [comment]
Plus this repo was previously open with feedback actively solicited from our customers, partners and community members.

I imagine it won’t look good for our “open, open” message, nor be seen to be consistent with our stated values regarding open source and transparency, should people realise this repo has been retroactively taken private without explanation

**Comment by dirkmueller** [comment]
these two are not related. suse.github.io is serving the base domain, open-source-policy (and any other repository under the SUSE/ org) is mapped as a subdirectory beneath that.
