### ISSUE TITLE
Icon on top left is not displayed correctly

### ISSUE THREAD

**Issue by lkocman** [SUSE/suse.github.io#20]
![missing-icon](https://user-images.githubusercontent.com/510119/148226018-e5165f2b-5af3-42df-bdce-12b7d2de5ecb.png)

**Comment by dirkmueller** [comment]
@lkocman yes, the whole branding is wrong. @kwwii is working on a properly branded version starting ~ next week.

**Comment by dirkmueller** [comment]
Fixed by https://github.com/SUSE/project-portal/pull/8
