### ISSUE TITLE
Collect products we produce

### ISSUE THREAD

**Issue by hennevogel** [SUSE/suse.github.io#7]
Stuff that many people download, install and use on a daily basis

**Comment by hennevogel** [comment]
[openSUSE Leap](https://en.opensuse.org/Portal:42.1)

**Comment by hennevogel** [comment]
[openSUSE Tumbleweed](https://en.opensuse.org/Portal:Tumbleweed)

**Comment by hennevogel** [comment]
[openSUSE Evergreen](https://en.opensuse.org/openSUSE:Evergreen)

**Comment by hennevogel** [comment]
[openSUSE Education-Li-f-e](https://en.opensuse.org/openSUSE:Education-Li-f-e)

**Comment by hennevogel** [comment]
[ownCloud in a box](https://susestudio.com/a/TadMax/owncloud-in-a-box)

**Comment by cyphar** [comment]
* [Portus](https://github.com/SUSE/Portus)
* [zypper-docker](https://github.com/SUSE/zypper-docker)

**Comment by cornelius** [comment]
How is this different from "projects we drive"? I think it makes sense to have an own category for distributions, but project such as portus or zypper-docker I would put under the category "projects we drive".

**Comment by cyphar** [comment]
I agree with @cornelius. I think we should consider terminology like "we drive" is much more community-friendly than saying that "X is a product we produce". While it is true that we (at SUSE) produce products from free software projects, saying that the **project itself** is "produced by us" isn't the way it should be framed IMO.

**Comment by hennevogel** [comment]
I was thinking about not limiting this to the narrow definition of *distributions* or do you think ownCloud in a box is a distribution? :-)

**Comment by cornelius** [comment]
I would rather put ownCloud in a box under the "projects we drive" category. The distributions are special and big projects, so having them in their own category would make sense to me. In any case I would actually consider ownCloud in a box a private side project, not something done by SUSE.

**Comment by hennevogel** [comment]
In the meeting we just had we have decided that we're going to drop the *product* category and just go with projects we are major contributors to and projects we drive. I move the links over...
